<?php
bolt_decrypt( __FILE__ , 'zxU70O'); return 0;
##!!!##CgcKB2teamJwbV5gYh0+bW1ZSmxhYmlwOAoHCgdycGIdRmlpcmpma15xYllBXnFeX15wYllCaWxucmJrcVlDXmBxbG9mYnBZRV5wQ15gcWxvdjgKB3JwYh1GaWlyamZrXnFiWUFecV5fXnBiWUJpbG5yYmtxWUpsYWJpOAoHCgdgaV5wcB1QYm9zYm8dYnVxYmthcB1KbGFiaQoHeAoHHR0dHW1vbHFiYHFiYR0hZHJeb2FiYR06HVgkZmEkWjgKBwoHegoH